#############################################################################
# Makefile for building: trakker
# Generated by qmake (2.01a) (Qt 4.5.2) on: Sun Oct 25 11:00:14 2009
# Project:  trakker.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile trakker.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lfftw3 -lm -lQtGui -lQtNetwork -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		trakkercontroller.cpp \
		src/trakkermodel.cpp \
		src/trakker.cpp moc_trakkermodel.cpp \
		moc_trakker.cpp \
		qrc_application.cpp
OBJECTS       = main.o \
		trakkercontroller.o \
		trakkermodel.o \
		trakker.o \
		moc_trakkermodel.o \
		moc_trakker.o \
		qrc_application.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		trakker.pro
QMAKE_TARGET  = trakker
DESTDIR       = 
TARGET        = trakker

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_centralwidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: trakker.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile trakker.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile trakker.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/trakker1.0.0 || $(MKDIR) .tmp/trakker1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/trakker1.0.0/ && $(COPY_FILE) --parents trakkercontroller.h src/trakkermodel.h src/trakker.h .tmp/trakker1.0.0/ && $(COPY_FILE) --parents src/application.qrc .tmp/trakker1.0.0/ && $(COPY_FILE) --parents main.cpp trakkercontroller.cpp src/trakkermodel.cpp src/trakker.cpp .tmp/trakker1.0.0/ && $(COPY_FILE) --parents centralwidget.ui .tmp/trakker1.0.0/ && (cd `dirname .tmp/trakker1.0.0` && $(TAR) trakker1.0.0.tar trakker1.0.0 && $(COMPRESS) trakker1.0.0.tar) && $(MOVE) `dirname .tmp/trakker1.0.0`/trakker1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/trakker1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_trakkermodel.cpp moc_trakker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_trakkermodel.cpp moc_trakker.cpp
moc_trakkermodel.cpp: src/trakkermodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/trakkermodel.h -o moc_trakkermodel.cpp

moc_trakker.cpp: forms/centralwidget.h \
		src/trakker.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/trakker.h -o moc_trakker.cpp

compiler_rcc_make_all: qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp
qrc_application.cpp: src/application.qrc \
		src/fileopen.xpm \
		src/filesave.xpm \
		src/editcopy.xpm \
		src/filenew.xpm \
		src/editpaste.xpm \
		src/editcut.xpm
	/usr/bin/rcc -name application src/application.qrc -o qrc_application.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_centralwidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_centralwidget.h
ui_centralwidget.h: centralwidget.ui
	/usr/bin/uic-qt4 centralwidget.ui -o ui_centralwidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp src/trakker.h \
		forms/centralwidget.h \
		trakkercontroller.h \
		src/trakkermodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

trakkercontroller.o: trakkercontroller.cpp trakkercontroller.h \
		src/trakkermodel.h \
		src/trakker.h \
		forms/centralwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trakkercontroller.o trakkercontroller.cpp

trakkermodel.o: src/trakkermodel.cpp src/trakkermodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trakkermodel.o src/trakkermodel.cpp

trakker.o: src/trakker.cpp src/trakker.h \
		forms/centralwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trakker.o src/trakker.cpp

moc_trakkermodel.o: moc_trakkermodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_trakkermodel.o moc_trakkermodel.cpp

moc_trakker.o: moc_trakker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_trakker.o moc_trakker.cpp

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

